### ISSUE TITLE
Support CIDR in allow_list

### ISSUE THREAD

**Issue by mdouchement** [mdouchement/seikan#7]
```yml
allow_list:
  - localhost:5000
  - endpoint: localhost:5001
    ignore_errors:
      # You can build your Golang's regexp on https://regex101.com/
      - connection refused
   ###### CIDR proposal
   - type: cidr
     network: 127.0.0.0/8
```
